use std::path::PathBuf;

#[allow(unused_imports)]
use crate::changes::validate_change_id;
#[allow(unused_imports)]
use crate::grammar::{SectionPresence, parse_delta_specification};
#[allow(unused_imports)]
use crate::interchange::detect::{
    ACTIVE_DECISIONS_DIR, ACTIVE_DESIGN_FILE, ACTIVE_PROPOSAL_FILE, ACTIVE_SPECS_DIR,
    ACTIVE_TASKS_FILE, STAGING_COUNTER, rename_no_replace,
};
#[allow(unused_imports)]
use crate::interchange::plan::{DeltaWarning, DeltaWarningKind, InterchangeError, NoteWrite};
#[allow(unused_imports)]
use crate::interchange::proof::strip_leading_h1;
#[allow(unused_imports)]
use crate::worknotes::{WorkChecklist, WorkNoteError, parse_work_note};

/// Staging result for an active tree's notebook writes; the caller
/// commits via `commit_active_staging` after every entry's stage
/// has succeeded (R7 fourth re-review 2026-07-25 — multi-entry
/// import all-or-nothing across entries).
pub struct ActiveStaging {
    /// Absolute path to the staging folder under the notebook.
    pub staging_full: PathBuf,
    /// Absolute path to the real proposals/<change_id>/ folder.
    pub real_full: PathBuf,
}

/// Stages the per-note actions generated by `import_active_tree` to
/// the notebook under a sibling
/// `proposals/<change_id>.staging-<counter>/` folder. Returns
/// without committing; the caller invokes
/// `commit_active_staging` after every entry's stage has
/// succeeded. On any per-write failure the staging folder is
/// removed before returning. POSIX-atomic `rename_no_replace`
/// publishes a clean batch; an EEXIST at the publish boundary is
/// the residual `Reserved`-style protection.
///
/// **v0.3.0-pause**: this function calls `client.add_note` and
/// `ensure_folder`, each of which auto-checkpoints the notebook
/// Git worktree. The notebook MCP Owner's fourth ring-1 re-review
/// called out the structural incompatibility: a notebook tree
/// created by these per-call checkpoints cannot be undone by a
/// subsequent filesystem rename, so the published state diverges
/// from the staged state. Active filesystem-tree ingest is
/// therefore paused in v0.3.0 pending an NbApi 0.3 notebook
/// transaction/checkpoint primitive with Git/index locking. The
/// source is preserved in tree under `#[cfg(any())]` and in git
/// history; with the gate off, the v0.3.0 execute path emits a
/// `paused`-state `PlanEntry::ActiveWrite` entry instead.
///
/// R7_F7 final-stack (third re-review 2026-07-25).
#[cfg(any())]
#[allow(dead_code)]
pub async fn stage_active_notes(
    client: &nb_api::NbClient,
    change_id: &str,
    writes: &[NoteWrite],
    notebook_name: &str,
) -> Result<ActiveStaging, crate::operations::OperationError> {
    let notebook = Some(notebook_name);
    let staging_counter = STAGING_COUNTER.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    let staging_change_id = format!("{change_id}.staging-{staging_counter}");
    let real_root = format!("proposals/{change_id}");
    let staging_root = format!("proposals/{staging_change_id}");

    ensure_folder(client, &staging_root, notebook).await?;
    let mut subfolders: Vec<String> = Vec::new();
    for write in writes {
        if !write.folder.is_empty() && !subfolders.contains(&write.folder) {
            subfolders.push(write.folder.clone());
        }
    }
    for subfolder in subfolders {
        let folder = format!("{staging_root}/{subfolder}");
        ensure_folder(client, &folder, notebook).await?;
    }

    let mut write_failures: Vec<(String, String)> = Vec::new();
    for write in writes {
        let folder = if write.folder.is_empty() {
            staging_root.clone()
        } else {
            format!("{staging_root}/{}", write.folder)
        };
        let write_result = if write.is_todo {
            write_todo_note(client, change_id, &folder, &write.content, notebook_name).await
        } else {
            client
                .add_note(
                    Some(&write.title),
                    &write.content,
                    &[],
                    Some(&folder),
                    notebook,
                )
                .await
                .map(|_| ())
                .map_err(crate::operations::OperationError::from)
        };
        if let Err(error) = write_result {
            write_failures.push((change_id.to_string(), format!("{error}")));
            break;
        }
    }

    if !write_failures.is_empty() {
        if let Ok(notebook_path) = client.show_notebook_path(notebook).await {
            let staging_full = notebook_path.join(&staging_root);
            let _ = std::fs::remove_dir_all(&staging_full);
        }
        return Err(crate::operations::OperationError::NoteRead {
            path: PathBuf::from(format!("<staging:{staging_root}>")),
            source: std::io::Error::other(format!(
                "staged notebook write failed and was rolled back: {} failure(s); \
                 first: {}",
                write_failures.len(),
                write_failures
                    .first()
                    .map(|(_, msg)| msg.clone())
                    .unwrap_or_default()
            )),
        });
    }

    let notebook_path = client.show_notebook_path(notebook).await?;
    let real_full = notebook_path.join(&real_root);
    let staging_full = notebook_path.join(&staging_root);
    Ok(ActiveStaging {
        staging_full,
        real_full,
    })
}

/// Commits a previously staged active tree by atomic-renaming the
/// staging folder into the real path. Uses `rename_no_replace` so
/// an occupant appearing between staging and commit returns
/// EEXIST atomically (Linux) or refuses (non-Linux).
/// **v0.3.0-pause**: see `stage_active_notes`. Gated behind
/// `#[cfg(any())]`; restored by the 0.3.0-resume cycle.
#[cfg(any())]
#[allow(dead_code)]
pub async fn commit_active_staging(
    client: &nb_api::NbClient,
    staging: ActiveStaging,
) -> Result<(), crate::operations::OperationError> {
    let notebook_name = "commit_active_staging_uses_resolved_path";
    let _ = (client, notebook_name);
    match rename_no_replace(&staging.staging_full, &staging.real_full) {
        Ok(()) => Ok(()),
        Err(error) => Err(crate::operations::OperationError::NoteRead {
            path: staging.real_full.clone(),
            source: std::io::Error::other(format!(
                "cannot publish staged notebook writes: {error}; \
                 staging folder at {} preserved for manual reconciliation",
                staging.staging_full.display()
            )),
        }),
    }
}

/// Writes the per-note actions generated by `import_active_tree` to
/// the notebook. Convenience wrapper that stages and immediately
/// commits; callers that need multi-entry atomicity should use
/// `stage_active_notes` and `commit_active_staging` directly.
///
/// **v0.3.0-pause**: see `stage_active_notes`. Gated behind
/// `#[cfg(any())]`; restored by the 0.3.0-resume cycle.
#[cfg(any())]
#[allow(dead_code)]
pub async fn write_active_notes(
    client: &nb_api::NbClient,
    change_id: &str,
    writes: &[NoteWrite],
    notebook_name: &str,
) -> Result<(), crate::operations::OperationError> {
    let staging = stage_active_notes(client, change_id, writes, notebook_name).await?;
    commit_active_staging(client, staging).await
}

/// Writes the work todo note directly to the notebook filesystem
/// to preserve `[x]` / `[ ]` checkbox state. `nb-api`'s
/// `add_todo` creates a fresh todo with no checked items, so the
/// only way to round-trip the source `tasks.md` faithfully is to
/// overwrite the file after creation.
///
/// **v0.3.0-pause**: see `stage_active_notes`. Gated behind
/// `#[cfg(any())]`; restored by the 0.3.0-resume cycle.
#[cfg(any())]
#[allow(dead_code)]
pub async fn write_todo_note(
    client: &nb_api::NbClient,
    change_id: &str,
    folder: &str,
    body: &str,
    notebook_name: &str,
) -> Result<(), crate::operations::OperationError> {
    let notebook = Some(notebook_name);
    let description = format!("Execution checklist for {change_id}.");
    client
        .add_todo(
            "work",
            Some(&description),
            &[],
            &["nbspec".to_string()],
            Some(folder),
            notebook,
        )
        .await?;
    let notebook_path = client.show_notebook_path(notebook).await?;
    let todo_path = notebook_path.join(folder).join("work.todo.md");
    std::fs::write(&todo_path, body).map_err(|source| {
        crate::operations::OperationError::NoteRead {
            path: todo_path,
            source,
        }
    })?;
    Ok(())
}

/// **v0.3.0-pause**: see `stage_active_notes`. Gated behind
/// `#[cfg(any())]`; restored by the 0.3.0-resume cycle.
#[cfg(any())]
#[allow(dead_code)]
pub async fn ensure_folder(
    client: &nb_api::NbClient,
    folder: &str,
    notebook: Option<&str>,
) -> Result<(), crate::operations::OperationError> {
    let listing = client
        .list_notes(Some(folder), &[], Some(1), notebook)
        .await;
    if listing.is_ok() {
        return Ok(());
    }
    client.add_folder(folder, notebook).await?;
    Ok(())
}

/// Maps an active change tree into the notebook namespace. Reads
/// every artifact the tree carries, normalises the proposal H1 to
/// the schema's selector-stable form, parses `tasks.md` into a
/// `work` checklist, and synthesises a `meta` control-plane note
/// with `migrated: true` provenance.
///
/// Returns the per-note writes, the warnings (MODIFIED/REMOVED
/// deltas the merge path will refuse to materialise), and the
/// synthesized meta content so the caller can attach them to the
/// plan or write them through `nb-api`.
///
/// **v0.3.0-pause**: gated behind `#[cfg(any())]`. The function
/// itself is read-only (it inspects source files and produces
/// writes + delta warnings), but it exists exclusively to feed
/// the `write_active_notes` / `write_todo_note` notebook-mutation
/// path, which is paused in v0.3.0 pending an NbApi 0.3 notebook
/// transaction/checkpoint primitive. The 0.3.0-resume cycle
/// restores this body from source (and git history) and feeds
/// the writes into the staged-then-committed `stage_active_notes`
/// flow.
///
/// # Errors
///
/// Returns [`InterchangeError::SourceRead`] when a required source
/// file is missing or unreadable, [`InterchangeError::TasksParse`]
/// when `tasks.md` is malformed, and [`InterchangeError::Collision`]
/// when the target notebook namespace already exists.
#[cfg(any())]
#[allow(dead_code)]
pub fn import_active_tree(
    tree: &crate::interchange::detect::ActiveTree,
    existing_namespaces: &[String],
) -> Result<(Vec<NoteWrite>, Vec<DeltaWarning>, String), InterchangeError> {
    if existing_namespaces.iter().any(|id| id == &tree.change_id) {
        return Err(InterchangeError::Collision(tree.change_id.clone()));
    }
    let proposal_source = read_source_file(&tree.root.join(ACTIVE_PROPOSAL_FILE))?;
    let proposal_content = normalize_proposal_h1(&proposal_source, &tree.change_id);
    let mut writes: Vec<NoteWrite> = Vec::new();
    writes.push(NoteWrite {
        folder: String::new(),
        title: "proposal".to_string(),
        content: proposal_content,
        is_todo: false,
    });

    let mut warnings: Vec<DeltaWarning> = Vec::new();

    let specs_root = tree.root.join(ACTIVE_SPECS_DIR);
    if specs_root.is_dir() {
        let specs = collect_capability_specs(&specs_root)?;
        for (capability, content) in specs {
            warnings.extend(delta_warnings_for_spec(
                &format!("specifications/{capability}.md"),
                &content,
            ));
            writes.push(NoteWrite {
                folder: "specifications".to_string(),
                title: capability.clone(),
                content: strip_leading_h1(&content),
                is_todo: false,
            });
        }
    }

    let design_path = tree.root.join(ACTIVE_DESIGN_FILE);
    if design_path.is_file() {
        let design_content = read_source_file(&design_path)?;
        writes.push(NoteWrite {
            folder: "designs".to_string(),
            title: "main".to_string(),
            content: strip_leading_h1(&design_content),
            is_todo: false,
        });
    }

    let decisions_root = tree.root.join(ACTIVE_DECISIONS_DIR);
    if decisions_root.is_dir() {
        let decisions = collect_decisions(&decisions_root)?;
        for (name, content) in decisions {
            writes.push(NoteWrite {
                folder: "decisions".to_string(),
                title: name.clone(),
                content: strip_leading_h1(&content),
                is_todo: false,
            });
        }
    }

    let tasks_path = tree.root.join(ACTIVE_TASKS_FILE);
    if tasks_path.is_file() {
        let tasks_content = read_source_file(&tasks_path)?;
        let checklist = parse_work_note(&tasks_content)?;
        writes.push(NoteWrite {
            folder: String::new(),
            title: "work".to_string(),
            content: render_work_note_body(&tree.change_id, &checklist),
            is_todo: true,
        });
    }

    let meta_content = render_meta_with_provenance(&tree.change_id, &tree.root)?;
    writes.push(NoteWrite {
        folder: String::new(),
        title: "meta".to_string(),
        content: meta_content.clone(),
        is_todo: false,
    });

    Ok((writes, warnings, meta_content))
}

/// Reads a filesystem source file under an active change tree,
/// surfacing a typed `InterchangeError::SourceRead` on failure.
#[cfg(any())] // v0.3.0-pause: restored by the 0.3.0-resume cycle
#[allow(dead_code)]
fn read_source_file(path: &std::path::Path) -> Result<String, InterchangeError> {
    std::fs::read_to_string(path).map_err(|source| InterchangeError::SourceRead {
        path: path.to_path_buf(),
        source,
    })
}

/// Rewrites the proposal H1 to the schema-stable form
/// `# <change-id>`. The H1 is load-bearing: notebook selectors
/// resolve from it, so a free-form H1 in a classic tree would
/// silently break every selector downstream. When the source H1
/// is already in selector-stable form, the content is returned
/// untouched.
#[cfg(any())] // v0.3.0-pause: restored by the 0.3.0-resume cycle
#[allow(dead_code)]
fn normalize_proposal_h1(content: &str, change_id: &str) -> String {
    let expected = format!("# {change_id}");
    let mut lines = content.lines();
    match lines.next() {
        Some(first) if first.trim() == expected => content.to_string(),
        _ => {
            let mut output = String::new();
            output.push_str(&expected);
            output.push('\n');
            for line in lines {
                output.push_str(line);
                output.push('\n');
            }
            if !content.ends_with('\n') && !output.ends_with('\n') {
                output.push('\n');
            }
            output
        }
    }
}

/// Reads the source proposal content, returning a path-anchored
/// error on failure.
#[cfg(any())] // v0.3.0-pause: restored by the 0.3.0-resume cycle
#[allow(dead_code)]
fn render_meta_with_provenance(
    change_id: &str,
    source_root: &std::path::Path,
) -> Result<String, InterchangeError> {
    use serde_json::json;
    let source_path = source_root.display().to_string();
    let payload = json!({
        "meta_version": 1,
        "change_id": change_id,
        "title": null,
        "status": "draft",
        "schema": "nbspec-default",
        "notebook": null,
        "created_at": null,
        "updated_at": null,
        "repository_commits": [],
        "migrated": true,
        "source_path": source_path,
    });
    Ok(format!(
        "```json\n{}\n```\n",
        serde_json::to_string_pretty(&payload).unwrap_or_default()
    ))
}

/// Walks the `<tree>/specs/` directory and returns
/// `(capability_name, spec_content)` pairs in capability-name order.
/// Each capability is a subdirectory carrying a single `spec.md`.
/// Returns an empty Vec when the directory holds no capabilities.
#[cfg(any())] // v0.3.0-pause: restored by the 0.3.0-resume cycle
#[allow(dead_code)]
fn collect_capability_specs(
    specs_root: &std::path::Path,
) -> Result<Vec<(String, String)>, InterchangeError> {
    let mut capabilities: Vec<(String, String)> = Vec::new();
    let entries = std::fs::read_dir(specs_root).map_err(|source| InterchangeError::SourceRead {
        path: specs_root.to_path_buf(),
        source,
    })?;
    let mut names: Vec<String> = Vec::new();
    for entry in entries.flatten() {
        if !entry.path().is_dir() {
            continue;
        }
        if let Ok(name) = entry.file_name().into_string() {
            names.push(name);
        }
    }
    names.sort();
    for name in names {
        let capability_root = specs_root.join(&name);
        let spec_file = capability_root.join("spec.md");
        if !spec_file.is_file() {
            // A capability without spec.md is silently skipped;
            // the source tree is loose enough that half-authored
            // capabilities are possible, and the operator's
            // intent (an empty spec) is to leave them out.
            continue;
        }
        let content = read_source_file(&spec_file)?;
        capabilities.push((name, content));
    }
    Ok(capabilities)
}

/// Walks the `<tree>/decisions/` directory and returns
/// `(decision_name, content)` pairs in name order. Decision
/// filenames are preserved because they are materialization
/// targets; arbitrary-named files are accepted to prove
/// name-agnosticism per `nbspec:ideas/7`.
#[cfg(any())] // v0.3.0-pause: restored by the 0.3.0-resume cycle
#[allow(dead_code)]
fn collect_decisions(
    decisions_root: &std::path::Path,
) -> Result<Vec<(String, String)>, InterchangeError> {
    let mut decisions: Vec<(String, String)> = Vec::new();
    let entries =
        std::fs::read_dir(decisions_root).map_err(|source| InterchangeError::SourceRead {
            path: decisions_root.to_path_buf(),
            source,
        })?;
    let mut names: Vec<(String, PathBuf)> = Vec::new();
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        if path.extension().and_then(|ext| ext.to_str()) != Some("md") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        names.push((stem.to_string(), path));
    }
    names.sort();
    for (name, path) in names {
        let content = read_source_file(&path)?;
        decisions.push((name, content));
    }
    Ok(decisions)
}

/// Returns the delta warnings implied by `content`. The merge path
/// only materialises `ADDED` requirements; `MODIFIED` / `REMOVED`
/// / `RENAMED` sections are warned at import time so the operator
/// knows they will fail to materialise downstream.
#[cfg(any())] // v0.3.0-pause: restored by the 0.3.0-resume cycle
#[allow(dead_code)]
fn delta_warnings_for_spec(note_path: &str, content: &str) -> Vec<DeltaWarning> {
    let delta = parse_delta_specification(content);
    if delta.presence == SectionPresence::default() {
        return Vec::new();
    }
    let mut warnings = Vec::new();
    if delta.presence.modified {
        warnings.push(DeltaWarning {
            note_path: note_path.to_string(),
            kind: DeltaWarningKind::Modified,
        });
    }
    if delta.presence.removed {
        warnings.push(DeltaWarning {
            note_path: note_path.to_string(),
            kind: DeltaWarningKind::Removed,
        });
    }
    if delta.presence.renamed {
        warnings.push(DeltaWarning {
            note_path: note_path.to_string(),
            kind: DeltaWarningKind::Renamed,
        });
    }
    warnings
}

/// Renders a `work` todo note body from a parsed checklist. The
/// title is `# [ ]/x Execution checklist for <change-id>` so the
/// notebook's `display` path recognizes the todo note. Tasks are
/// emitted in their original order with checkbox state preserved.
#[cfg(any())] // v0.3.0-pause: restored by the 0.3.0-resume cycle
#[allow(dead_code)]
fn render_work_note_body(change_id: &str, checklist: &WorkChecklist) -> String {
    let title_marker = if checklist.complete { "[x]" } else { "[ ]" };
    let title = checklist
        .title
        .clone()
        .unwrap_or_else(|| format!("Execution checklist for {change_id}."));
    let mut body = String::new();
    body.push_str(&format!("# {title_marker} {title}\n"));
    for item in &checklist.items {
        let marker = if item.complete { "x" } else { " " };
        body.push_str(&format!("- [{marker}] {}\n", item.text));
    }
    body
}
